# Generated by Django 4.0.10 on 2023-03-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('palettes', '0002_palette_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palettes', models.ManyToManyField(blank=True, related_name='teams', to='palettes.palette')),
            ],
        ),
    ]
